### ISSUE TITLE
Big Dot stuck on typing

### ISSUE THREAD

**Issue by biga94** [alexpinel/Dot#15]
First of all, thank you for this amazing project. I'm in awe.

Unfortunately, I'm not able to use it on my Macbook Pro M1 Max.. At first opening, I had to download Mistral model as the application suggests; however, due to connection problem I had to stop the application waiting for a stable connection and reopen the application. Unfortunately, the application was not able to restart the model download. I've tried to uninstall and re-install the application several times but the situation is always the same. At first I thought the model was downloaded in background, but as soon as I try to input text to Big Dot, chatbot's keep stuck on "Dot is typing...".

Do you know how to force the correct download of the model?

Best,

DB

**Comment by alexpinel** [comment]
Hi! 

The default LLM is downloaded in a folder called Dot-Data that is stored in documents, if you delete the llm file the app will automatically attempt to reinstall once you open it again.

Are you using the packaged app or are you trying to build it from the source code? if so there are still a few details I need to add on the README, so please let me know if you are facing any other issues!

Best,

Alex

**Comment by biga94** [comment]
Dear @alexpinel thank you for your quick and clear response!
I was able to download correctly phi3 as required. :)
I'm using the packaged app.

I would give just a suggestion:
since Documents folder is often synced with iCloud, downloading 2.3 GB of model inside, could lead to a lack of space or also download stopping. Probably would be better to select the folder where to download the LLM.
However, really nice job. Congrats!!

Best,

DB

**Comment by alexpinel** [comment]
Thanks!

And that is a really valid point, I completely forgot about iCloud! Will correct this issue asap.

Best,

Alex
